version: '3.8'

services:

nest:
  command: npm run start:dev
  volumes:
    - ./backend
  environment:
  - NODE_ENV=development

next:
  command: npm run dev
  volumes:
    - ./web
  environment: 
   - NODE_ENV=development