name: LoC Badge

on: [push]
permissions: 
    contents: write

jobs:
  Loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make Code Badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./output/badge.svg
          ignore: 'node_modules'

      - name: Deploy to action-data branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: Loc-Image
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
